### ISSUE TITLE
Transpile Examples

### ISSUE THREAD

**Issue by meibegger** [bp74/StageXL_Samples#11]
I downloaded the sample files and created a "new project" with them. 
But i can not build it, because the stagexl_X dependencies time out ... 

So i copied the video_example to a new project and uncommented the stagexl_X dependencies from the yaml.
But the transpiled index.dart.js has 230K - and http://www.stagexl.org/samples/video/index.dart.js only has 80K.

Do you have any hints on what the difference might be?

**Comment by bp74** [comment]
I just downloaded the index.dart.js file and it is 223KB in size, where do you see the 80KB file? Do you get the timeout when you do "Pub get" or "Pup upgrade" ? If this is the case you should check what's wrong with Pub.

**Comment by bp74** [comment]
Ah - maybe you see the 80K file because it is compressed with GZIP. The file is stored as compressed file on the server, when a browser downloads it, it will automatically uncompressed and you get the javascript file.

**Comment by meibegger** [comment]
Ah OK! Didn't think of the GZIP - sorry - only checked the Net-"console" and got shocked by my 230K ... THANKS!



Yes - something wrong with Pub, i guess ... Both timeout (today)  ... 
```
Downloading stagexl_spine 0.4.0...
Timed out after 30.0s while downloading https://pub.dartlang.org/packages/stagexl_spine/versions/0.4.0.tar.gz.
This is likely a transient error. Please try again later.
package:pub/src/io.dart 831  timeout.<fn>
dart:isolate                 _RawReceivePortImpl._handleMessage
This is an unexpected error. Please run

    pub --trace upgrade

and include the results in a bug report on http://dartbug.com/new.
```
Trace is
```
ERR : Timed out after 30.0s while downloading https://pub.dartlang.org/packages/stagexl_spine/versions/0.4.0.tar.gz.
    | This is likely a transient error. Please try again later.
FINE: Exception type: TimeoutException
ERR : package:pub/src/io.dart 831  timeout.<fn>
    | dart:isolate                 _RawReceivePortImpl._handleMessage
    | ===== asynchronous gap ===========================
    | dart:async                              Timer.Timer
    | package:pub/src/io.dart 820             timeout
    | package:pub/src/source/hosted.dart 194  HostedSource._download.<fn>.<fn>
    | dart:isolate                            _RawReceivePortImpl._handleMessage
    | ===== asynchronous gap ===========================
    | dart:async                              _Future.then
    | package:pub/src/source/hosted.dart 193  HostedSource._download.<fn>
    | dart:async                              Future.Future.sync
    | package:pub/src/source/hosted.dart 184  HostedSource._download
    | package:pub/src/source/hosted.dart 93   HostedSource.downloadToSystemCache.<fn>
    | dart:isolate                            _RawReceivePortImpl._handleMessage
    | ===== asynchronous gap ===========================
    | dart:async                             _Future.then
    | package:pub/src/source/hosted.dart 86  HostedSource.downloadToSystemCache
    | package:pub/src/source/cached.dart 51  CachedSource.get
    | package:pub/src/entrypoint.dart 365    Entrypoint._get.<fn>
    | dart:async                             Future.Future.sync
    | package:pub/src/entrypoint.dart 357    Entrypoint._get
    | dart:async                             Future.wait
    | package:pub/src/entrypoint.dart 133    Entrypoint.acquireDependencies.<async>
    | dart:isolate                           _RawReceivePortImpl._handleMessage
    | ===== asynchronous gap ===========================
    | dart:async                           _Future.then
    | package:pub/src/entrypoint.dart 115  Entrypoint.acquireDependencies.<async>
    | dart:isolate                         _RawReceivePortImpl._handleMessage
    | ===== asynchronous gap ===========================
    | dart:async                               Future.Future.microtask
    | package:pub/src/entrypoint.dart          Entrypoint.acquireDependencies
    | package:pub/src/command/upgrade.dart 34  UpgradeCommand.run.<async>
    | dart:isolate                             _RawReceivePortImpl._handleMessage
    | ===== asynchronous gap ===========================
    | dart:async                               Future.Future.microtask
    | package:pub/src/command/upgrade.dart     UpgradeCommand.run
    | package:args/command_runner.dart 178     CommandRunner.runCommand.<fn>
    | dart:async                               Future.Future.sync
    | package:args/command_runner.dart 131     CommandRunner.runCommand
    | package:pub/src/command_runner.dart 121  PubCommandRunner.runCommand.<async>.<fn>
    | dart:async                               Future.Future.sync
    | package:pub/src/utils.dart 103           captureErrors.<fn>
    | package:stack_trace/src/chain.dart 78    Chain.capture
    | package:pub/src/utils.dart 117           captureErrors
    | package:pub/src/command_runner.dart 121  PubCommandRunner.runCommand.<async>
    | dart:isolate                             _RawReceivePortImpl._handleMessage
---- End log transcript ----
```

**Comment by bp74** [comment]
Yes looks like a problem with Pub. When i download the file now it is fast. But still the StageXL_Spine file is pretty big (8.8MB). Maybe i should remove some of the samples in the next release or make them smaller :)

**Comment by meibegger** [comment]
Hm - i have a very slow internet connection ... downloading takes a little bit > 30sec ... but Pub can't seriously mean that by "time out"???

**Comment by bp74** [comment]
No I don't think so. Probably just a temporary problem with the pub servers.

**Comment by meibegger** [comment]
https://github.com/dart-lang/sdk/issues/23833#issuecomment-120804148

**Comment by bp74** [comment]
Thanks for opening the issue. It is really strange that pub has this strange timeout behavior.

Btw. totally unrelated to this issue ... It's interesting to know that Dart does not transpile to JavaScript. Languages like TypeScript or CoffeeScript do transpile, which is nothing more than a pretty stupid translation to JavaScript. But Dart is much more clever! In fact it's a real compilation with many optimizations like inlining, dead code elimination (tree shaking), loop optimizations etc. I just say that because it is an important difference if you explain Dart to other people and want to highlight the difference to TypeScript.

**Comment by meibegger** [comment]
I agree - the timeout behavior seems pretty unlogical ...

And thanks for pointing this out! You are right of course. 
PHPStorm calls it transpiling ... that's why i made this mistake ..

I read in the FAQs, that Dart strives to to generate small JS output. I am sure, the compiler does great work in doing this, but it is also worth noting, that the basic overhead seems to be relatively big - so using it for small web applications is questionable ... (see the 223K for the videoplayer ...)

**Comment by meibegger** [comment]
And it does not support IE9 ... but there are still a lot of big companies (at least in Austria) using IE9 ...

**Comment by bp74** [comment]
Yes my company is supporting a web based administration tool which was developed for IE 7, it's a shame to tell customers that they have to use IE or "IE Tab" in Chrome. Btw. where are you located in Austria?

**Comment by meibegger** [comment]
ouch ;)
Vienna ...
