### ISSUE TITLE
TextField sample with big size

### ISSUE THREAD

**Issue by xavierhainaux** [bp74/StageXL_Samples#8]
Hello Bernhard,
Thank you for the great samples for textfield!
It seems though that there is a problem when using big font (> 128px).
For example, here is what I see for half the example:
![screen shot 2014-05-11 at 10 59 22](https://cloud.githubusercontent.com/assets/5110923/2938027/003711c2-d8eb-11e3-8c7c-d496e3e292db.png)

![screen shot 2014-05-11 at 10 59 09](https://cloud.githubusercontent.com/assets/5110923/2938026/f9c53bca-d8ea-11e3-80ec-d2c1459ecaad.png)

This is on a mac and on my android device. I cannot test on windows right now but I guess the problem is not there since you don't have it.
If we resize the textfield under 128px, everything is back to normal.
I suppose this is a bug on webkit for linux/mac platform. I don't know what we can do about it.

**Comment by bp74** [comment]
I think we can close this old issue, the fonts looks okay now (except some minor issus in Chrome in rare cases). Unfortunately there isn't much we can do about it.
